version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "80:80"   # Puerto HTTP
      - "443:443" # Puerto HTTPS
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf # Archivo de configuración Nginx
      - /etc/nginx/ssl:/etc/nginx/ssl                 # Certificados SSL (asegúrate de mapear la ruta correcta en tu servidor)
