version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "80:80"   # Puerto HTTP
      - "443:443" # Puerto HTTPS
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf   # Configuración de Nginx
      - /etc/ssl/certs/underhack_me.crt:/etc/ssl/certs/underhack_me.crt   # Certificado SSL
      - /etc/ssl/private/underhack.me.key:/etc/ssl/private/underhack.me.key  # Clave privada SSL
      - /etc/ssl/certs/underhack_me.ca-bundle:/etc/ssl/certs/underhack_me.ca-bundle
