name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Configurar el repositorio
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configurar SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


    # Construir la aplicación
    - name: Build the App
      run: |
        npm install
        npm run build

    # Copiar los archivos al servidor
    - name: Deploy to Server
      run: |
        scp -r dist/* $DEPLOY_USER@$DEPLOY_IP:$DEPLOY_PATH
        ssh $DEPLOY_USER@$DEPLOY_IP "docker-compose down && docker-compose up -d"
      env:
        DEPLOY_IP: ${{ secrets.DEPLOY_IP }}
        DEPLOY_NAME: ${{ secrets.DEPLOY_NAME }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}